const data = [{
  value: '游戏',
  label: '游戏',
  children: [{
    value: '手机游戏',
    label: '手机游戏'
  }, {
    value: '网页游戏',
    label: '网页游戏'
  }, {
    value: '客户端游戏',
    label: '客户端游戏'
  }, {
    value: 'H5游戏/小游戏',
    label: 'H5游戏/小游戏'
  }, {
    value: '渲染',
    label: '渲染'
  }, {
    value: '电视游戏',
    label: '电视游戏'
  }, {
    value: '第三方服务',
    label: '第三方服务'
  }, {
    value: '游戏平台',
    label: '游戏平台'
  }, {
    value: 'VR游戏',
    label: 'VR游戏'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '网站',
  label: '网站',
  children: [{
    value: '企业网站',
    label: '企业网站'
  }, {
    value: '网建公司',
    label: '网建公司'
  }, {
    value: '个人站长',
    label: '个人站长'
  }, {
    value: '社区/论坛/博客',
    label: '社区/论坛/博客'
  }, {
    value: '移动H5建站',
    label: '移动H5建站'
  }, {
    value: '小程序开发',
    label: '小程序开发'
  }, {
    value: '公众号开发',
    label: '公众号开发'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '大数据与人工智能',
  label: '大数据与人工智能',
  children: [{
    value: '大数据基础服务',
    label: '大数据基础服务'
  }, {
    value: '大数据分析及可视化',
    label: '大数据分析及可视化'
  }, {
    value: '大数据安全',
    label: '大数据安全'
  }, {
    value: '计算机视觉',
    label: '计算机视觉'
  }, {
    value: '语音识别',
    label: '语音识别'
  }, {
    value: '自然语言处理',
    label: '自然语言处理'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '音视频',
  label: '音视频',
  children: [{
    value: '在线视频',
    label: '在线视频'
  }, {
    value: '安防监控',
    label: '安防监控'
  }, {
    value: '直播',
    label: '直播'
  }, {
    value: '渲染',
    label: '渲染'
  }, {
    value: '短视频',
    label: '短视频'
  }, {
    value: 'VR视频',
    label: 'VR视频'
  }, {
    value: '视频软件',
    label: '视频软件'
  }, {
    value: '视频设备',
    label: '视频设备'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '金融',
  label: '金融',
  children: [{
    value: '银行',
    label: '银行'
  }, {
    value: '保险',
    label: '保险'
  }, {
    value: '证券',
    label: '证券'
  }, {
    value: '信托/期货/基金',
    label: '信托/期货/基金'
  }, {
    value: '金融科技服务',
    label: '金融科技服务'
  }, {
    value: 'P2P/小贷',
    label: 'P2P/小贷'
  }, {
    value: '消费金融',
    label: '消费金融'
  }, {
    value: '交易所',
    label: '交易所'
  }, {
    value: '第三方支付',
    label: '第三方支付'
  }, {
    value: '金融媒体',
    label: '金融媒体'
  }, {
    value: '资产担保',
    label: '资产担保'
  }, {
    value: '资产评估/审计',
    label: '资产评估/审计'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '房地产',
  label: '房地产',
  children: [{
    value: '房地产开发',
    label: '房地产开发'
  }, {
    value: '商业地产和工业地产',
    label: '商业地产和工业地产'
  }, {
    value: '工程设计/建设和总包',
    label: '工程设计/建设和总包'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: 'IT服务/软件',
  label: 'IT服务/软件',
  children: [{
    value: 'CRM',
    label: 'CRM'
  }, {
    value: 'ERP',
    label: 'ERP'
  }, {
    value: 'BOSS',
    label: 'BOSS'
  }, {
    value: '财务软件',
    label: '财务软件'
  }, {
    value: 'OA',
    label: 'OA'
  }, {
    value: '软件开发',
    label: '软件开发'
  }, {
    value: '金融软件服务',
    label: '金融软件服务'
  }, {
    value: '系统安全',
    label: '系统安全'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '电子商务',
  label: '电子商务',
  children: [{
    value: 'B2B',
    label: 'B2B'
  }, {
    value: 'B2C',
    label: 'B2C'
  }, {
    value: 'C2C',
    label: 'C2C'
  }, {
    value: '团购导购',
    label: '团购导购'
  }, {
    value: '零售/商超/连锁',
    label: '零售/商超/连锁'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: 'O2O生活服务',
  label: 'O2O生活服务',
  children: [{
    value: '出行',
    label: '出行'
  }, {
    value: '农业/生鲜',
    label: '农业/生鲜'
  }, {
    value: '汽车服务',
    label: '汽车服务'
  }, {
    value: '二维码/wifi/pos',
    label: '二维码/wifi/pos'
  }, {
    value: '餐饮外送',
    label: '餐饮外送'
  }, {
    value: '婚嫁/美业',
    label: '婚嫁/美业'
  }, {
    value: '房产/家装',
    label: '房产/家装'
  }, {
    value: '社区/家政',
    label: '社区/家政'
  }, {
    value: '理财/卡券',
    label: '理财/卡券'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '交通运输业',
  label: '交通运输业',
  children: [{
    value: '航空公司',
    label: '航空公司'
  }, {
    value: '航运公司',
    label: '航运公司'
  }, {
    value: '公共交通/出租车',
    label: '公共交通/出租车'
  }, {
    value: '高速公路',
    label: '高速公路'
  }, {
    value: '铁路和轨道交通',
    label: '铁路和轨道交通'
  }, {
    value: '港口/机场/火车站',
    label: '港口/机场/火车站'
  }, {
    value: '物流服务供应商',
    label: '物流服务供应商'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '教育',
  label: '教育',
  children: [{
    value: '学术/科研',
    label: '学术/科研'
  }, {
    value: '学校和管理机构',
    label: '学校和管理机构'
  }, {
    value: '研究机构',
    label: '研究机构'
  }, {
    value: '培训类教育机构',
    label: '培训类教育机构'
  }, {
    value: '在线教育',
    label: '在线教育'
  }, {
    value: '远程教育',
    label: '远程教育'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '零售商和批发商',
  label: '零售商和批发商',
  children: [{
    value: '经销批发贸易公司/品牌商',
    label: '经销批发贸易公司/品牌商'
  }, {
    value: '大卖场/超市/便利店',
    label: '大卖场/超市/便利店'
  }, {
    value: '休闲娱乐',
    label: '休闲娱乐'
  }, {
    value: '商场/商业综合体',
    label: '商场/商业综合体'
  }, {
    value: '零售服务商/信息集成商',
    label: '零售服务商/信息集成商'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '媒体',
  label: '媒体',
  children: [{
    value: '报刊/出版社',
    label: '报刊/出版社'
  }, {
    value: '民营传媒',
    label: '民营传媒'
  }, {
    value: '互联网传媒',
    label: '互联网传媒'
  }, {
    value: '在线新闻',
    label: '在线新闻'
  }, {
    value: '在线广告',
    label: '在线广告'
  }, {
    value: '户外媒体',
    label: '户外媒体'
  }, {
    value: '广电/OTT',
    label: '广电/OTT'
  }, {
    value: '视频媒体',
    label: '视频媒体'
  }, {
    value: '影院',
    label: '影院'
  }, {
    value: 'VR电影',
    label: 'VR电影'
  }, {
    value: '影视相关',
    label: '影视相关'
  }, {
    value: '数字营销/程序化交易广告',
    label: '数字营销/程序化交易广告'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '通讯',
  label: '通讯',
  children: [{
    value: '运营商',
    label: '运营商'
  }, {
    value: '通讯设备',
    label: '通讯设备'
  }, {
    value: '手机厂商',
    label: '手机厂商'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '物联网/车联网',
  label: '物联网/车联网',
  children: [{
    value: '车联网',
    label: '车联网'
  }, {
    value: 'VR设备',
    label: 'VR设备'
  }, {
    value: '智能穿戴',
    label: '智能穿戴'
  }, {
    value: '智慧家居',
    label: '智慧家居'
  }, {
    value: '智能硬件',
    label: '智能硬件'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '旅游',
  label: '旅游',
  children: [{
    value: '旅游平台',
    label: '旅游平台'
  }, {
    value: '旅游管理机构',
    label: '旅游管理机构'
  }, {
    value: '旅行社',
    label: '旅行社'
  }, {
    value: '酒店',
    label: '酒店'
  }, {
    value: '票务',
    label: '票务'
  }, {
    value: '地图',
    label: '地图'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '消费品生产商',
  label: '消费品生产商',
  children: [{
    value: '食品/饮料/酒类',
    label: '食品/饮料/酒类'
  }, {
    value: '烟草',
    label: '烟草'
  }, {
    value: '快速消费品',
    label: '快速消费品'
  }, {
    value: '餐饮',
    label: '餐饮'
  }, {
    value: '服务百货/母婴',
    label: '服务百货/母婴'
  }, {
    value: '农业',
    label: '农业'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '医疗',
  label: '医疗',
  children: [{
    value: '医院/医疗机构',
    label: '医院/医疗机构'
  }, {
    value: '体检机构',
    label: '体检机构'
  }, {
    value: '化学/制药',
    label: '化学/制药'
  }, {
    value: '医疗器械',
    label: '医疗器械'
  }, {
    value: '生物科学',
    label: '生物科学'
  }, {
    value: '基因工程',
    label: '基因工程'
  }, {
    value: '在线医疗',
    label: '在线医疗'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '移动应用',
  label: '移动应用',
  children: [{
    value: '社交通讯',
    label: '社交通讯'
  }, {
    value: '生活娱乐',
    label: '生活娱乐'
  }, {
    value: '运动健康',
    label: '运动健康'
  }, {
    value: '丽人母婴',
    label: '丽人母婴'
  }, {
    value: '新闻阅读',
    label: '新闻阅读'
  }, {
    value: '图片图像',
    label: '图片图像'
  }, {
    value: '系统工具',
    label: '系统工具'
  }, {
    value: '应用市场',
    label: '应用市场'
  }, {
    value: '手机助手',
    label: '手机助手'
  }, {
    value: '其他应用',
    label: '其他应用'
  }]
}, {
  value: '云服务',
  label: '云服务',
  children: [{
    value: '云厂商',
    label: '云厂商'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '政府公共机构',
  label: '政府公共机构',
  children: [{
    value: '地方政府',
    label: '地方政府'
  }, {
    value: '部委',
    label: '部委'
  }, {
    value: '公安/安防',
    label: '公安/安防'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '制造业',
  label: '制造业',
  children: [{
    value: '军工国防',
    label: '军工国防'
  }, {
    value: '汽车业',
    label: '汽车业'
  }, {
    value: '半导体电子/光伏',
    label: '半导体电子/光伏'
  }, {
    value: '消费电子/家电',
    label: '消费电子/家电'
  }, {
    value: '外包制造服务',
    label: '外包制造服务'
  }, {
    value: '化工',
    label: '化工'
  }, {
    value: '重型设备/装备制造',
    label: '重型设备/装备制造'
  }, {
    value: '耐用品制造',
    label: '耐用品制造'
  }, {
    value: '工业品制造',
    label: '工业品制造'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '能源',
  label: '能源',
  children: [{
    value: '采矿',
    label: '采矿'
  }, {
    value: '冶金和钢铁',
    label: '冶金和钢铁'
  }, {
    value: '造纸和林业',
    label: '造纸和林业'
  }, {
    value: '建筑材料',
    label: '建筑材料'
  }, {
    value: '石油和天然气',
    label: '石油和天然气'
  }, {
    value: '电力',
    label: '电力'
  }, {
    value: '水务',
    label: '水务'
  }, {
    value: '燃气',
    label: '燃气'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '医药',
  label: '医药',
  children: [{
    value: '化学制药',
    label: '化学制药'
  }, {
    value: '医疗设备',
    label: '医疗设备'
  }, {
    value: '生物科学',
    label: '生物科学'
  }, {
    value: '基因工程',
    label: '基因工程'
  }, {
    value: '其他',
    label: '其他'
  }]
}, {
  value: '其他',
  label: '其他',
  children: [{
    value: '其他',
    label: '其他'
  }]
}]

export default data
